# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - blog.md
  # - about.md
  - me.md

footer: '在这片荒芜之地寻找更好的自己'

style: dark # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

#plugins:
#  - jekyll-seo-tag